title = input()
content = input()
command = input()
print("<h1>")
print(f"    {title}")
print("</h1>")
print("<article>")
print(f"    {content}")
print("</article>")
while command != "end of comments":
    print("<div>")
    print(f"    {command}")
    print("</div>")
    command = input()
